### ISSUE TITLE
can we not change the key if variable is not set?

### ISSUE THREAD

**Issue by ozbillwang** [cgmartin/envhandlebars#11]
When converting, if the variables, for example, `account_key`, are not set, the part of codes `{{ account_key }}`, will be blank.

Can we not change to blank if some variables are not set

**Comment by cgmartin** [comment]
Does the built in `if` helper help for your case? http://handlebarsjs.com/builtin_helpers.html
```
{{#if account_key}} {{account_key}} {{else}} Not blank {{/if}}
```

**Comment by ozbillwang** [comment]
Thanks. But I have not only one key, should I do that for each key?
