### ISSUE TITLE
include Ember Truth Helpers and Ember Composable Helpers?

### ISSUE THREAD

**Issue by luisdavim** [cgmartin/envhandlebars#6]
Hi, do you think it would be possible to include those extra helpers so that we could use more complex templates?

**Comment by cgmartin** [comment]
Hi @luisdavim thanks for this, but my first thought is that this would add several new dependencies that I'm not sure I'd want to maintain here. The original intent for `envhandlebars` was to be very specific to handlebars alone and its simple API. Its niche seems to be between `envsubst` (dead simple) and Chef, Ansible, `consul-template`, `confd`, etc. (complex).

What might be more appropriate is a separate project ie. `envembertemplate` that could extend from `envhandlebars` using the [custom helper bridge API](https://github.com/cgmartin/envhandlebars#custom-helpers-or-partials) and layer in all of the complex Ember template plugins and features. Maybe something you or others might be interested in creating?

**Comment by luisdavim** [comment]
Makes sense. I might give it a try when I have some spare time. 

Thanks.
